/**
 * @file
 *
 * This file was auto-generated by shacl2code 1.1.0. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <functional>
#include <optional>
#include <string>

#include "decode.hpp"
#include "objectset.hpp"

/* */
namespace SPDX {
namespace v3_0_1 {
/* */

using std::string_literals::operator""s;

// DecoderState
DecoderState::DecoderState(SHACLObjectSet *objectSet) : mObjectSet(objectSet) {}
DecoderState::~DecoderState() {}

std::string DecoderState::expandIRI(std::string const &iri) const {
  if (!mObjectSet) {
    return iri;
  }
  return mObjectSet->expandIRI(iri);
}

std::string DecoderState::compactIRI(std::string const &iri) const {
  if (!mObjectSet) {
    return iri;
  }
  return mObjectSet->compactIRI(iri);
}

// ElementDecoder
ElementDecoder::ElementDecoder(DecoderState &state) : mState(state) {}
ElementDecoder::~ElementDecoder() {}

// ValueDecoder
ValueDecoder::ValueDecoder(DecoderState &state) : ElementDecoder(state) {}
ValueDecoder::~ValueDecoder() {}

// ObjectDecoder
ObjectDecoder::ObjectDecoder(DecoderState &state) : ElementDecoder(state) {}
ObjectDecoder::~ObjectDecoder() {}

// ListDecoder
ListDecoder::ListDecoder(DecoderState &state) : ElementDecoder(state) {}
ListDecoder::~ListDecoder() {}

/* */
}
}
/* */
