/**
 * @file
 *
 * This file was auto-generated by shacl2code 1.1.0. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <functional>
#include <string>

#include "errorhandler.hpp"
#include "exceptions.hpp"
#include "objectpath.hpp"

/* */
namespace SPDX {
namespace v3_0_1 {
/* */

using std::string_literals::operator""s;

// DefaultErrorHandler
DefaultErrorHandler::DefaultErrorHandler() {}
DefaultErrorHandler::~DefaultErrorHandler() {}

void DefaultErrorHandler::handleValidationError(std::string const &message,
                                                ObjectPath const &path) {
  throw ValidationError(message, path.getPathString());
}

void DefaultErrorHandler::handleDeserializeError(std::string const &message,
                                                 ObjectPath const &path) {
  throw DeserializeError(message, path.getPathString());
}

DefaultErrorHandler DefaultErrorHandler::handler;

// NoopErrorHandler
NoopErrorHandler::NoopErrorHandler() {}
NoopErrorHandler::~NoopErrorHandler() {}

void NoopErrorHandler::handleValidationError(std::string const &message, ObjectPath const &path) {}

void NoopErrorHandler::handleDeserializeError(std::string const &message, ObjectPath const &path) {}

NoopErrorHandler NoopErrorHandler::handler;

/* */
}
}
/* */
