/**
 * @file
 *
 * This file was auto-generated by shacl2code 1.1.0. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <memory>
#include <set>
#include <string>
#include <unordered_set>

#include "link.hpp"
#include "objectpath.hpp"
#include "objectset.hpp"

/* */
namespace SPDX {
namespace v3_0_1 {
/* */

using std::string_literals::operator""s;

// LinkState
LinkState::LinkState(SHACLObjectSet *o, std::set<std::string> *m) : objectSet(o), missing(m) {}

std::shared_ptr<SHACLObject>
LinkState::findObjById(std::string const &id, std::shared_ptr<SHACLObject> const &dflt) const {
  return objectSet->findById(id, dflt);
}

/* */
}
}
/* */
