/**
 * @file
 *
 * This file was auto-generated by shacl2code 1.1.0. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <memory>

#include "object.hpp"
#include "objectpath.hpp"
#include "refproperty.hpp"
#include "walk.hpp"

/* */
namespace SPDX {
namespace v3_0_1 {
/* */

using std::string_literals::operator""s;

void RefPropertyHelper::walkSHACLObject(SHACLObject const *object, WalkCallback const &callback,
                                        ObjectPath &path) {
  object->walk(callback, path);
}

std::shared_ptr<SHACLObject> RefPropertyHelper::decodeSHACLObject(ObjectDecoder &decoder,
                                                                  TypeBase const *type,
                                                                  ErrorHandler &errorHandler,
                                                                  ObjectPath &path) {
  return SHACLObject::decode(decoder, type, errorHandler, path);
}

/* */
}
}
/* */
