/**
 * @file
 *
 * This file was auto-generated by shacl2code 1.1.0. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <memory>
#include <optional>
#include <string>

#include "object.hpp"
#include "type.hpp"

/* */
namespace SPDX {
namespace v3_0_1 {
/* */

// TypeBase
TypeBase::TypeBase(std::string &&typeIRI, std::optional<std::string> &&compactTypeIRI)
    : mTypeIRI(std::move(typeIRI)), mCompactTypeIRI(std::move(compactTypeIRI)) {
  SHACLObject::getIRITypeRegistry().insert({mTypeIRI, this});
  if (mCompactTypeIRI.has_value()) {
    SHACLObject::getCompactTypeRegistry().insert({mCompactTypeIRI.value(), this});
  }
}

TypeBase::~TypeBase() {}

bool TypeBase::isSubClassOf(TypeBase const *type) const { return isSubClassOf(type->getTypeIRI()); }

/* */
}
}
/* */
