/**
 * @file
 *
 * This file was auto-generated by shacl2code 1.1.0. DO NOT MANUALLY MODIFY IT
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "util.hpp"

#include <string>

/* */
namespace SPDX {
namespace v3_0_1 {
/* */

using std::string_literals::operator""s;

bool isBlankNode(std::string const &id) { return id.rfind("_:", 0) == 0; }

bool isIRI(std::string const &id) {
  if (isBlankNode(id)) {
    return false;
  }

  if (id.find(":") == std::string::npos) {
    return false;
  }

  return true;
}

/* */
}
}
/* */
